In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue'

requests.get(url)


#response 403 bcz wikepdia doesn allow this

In [3]:


url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

headers = {
    "User-Agent": "MyBot/1.0 (https://example.com/contact)"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.title.text)
else:
    print("Error:", response.status_code)

List of largest companies by revenue - Wikipedia

In [4]:
<table class="wikitable sortable sticky-header-multi sort-under jquery-tablesorter" style="text-align:left;" id="mwKQ">
<thead><tr id="mwKw">

SyntaxError: invalid syntax (2375594769.py, line 1)

In [ ]:
<table class="wikitable sortable plainrowheaders jquery-tablesorter" style="text-align: center" id="mwA6Y">

SyntaxError: invalid syntax (3761763678.py, line 1)

In [8]:
soup.find_all('table')[0]

<table class="wikitable sortable sticky-header-multi sort-under" id="mwKQ" style="text-align:left;">
<tbody id="mwKg"><tr id="mwKw">
<th id="mwLA" rowspan="2" scope="col">Ranks</th>
<th id="mwLQ" rowspan="2" scope="col">Name</th>
<th id="mwLg" rowspan="2" scope="col">Industry</th>
<th id="mwLw" scope="col">Revenue</th>
<th id="mwMA" scope="col">Profit</th>
<th id="mwMQ" rowspan="2" scope="col">Employees</th>
<th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>
<th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>
<th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th></tr>
<tr id="mwPA">
<th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th></tr>
<tr id="mwPw">
<th id="mwQA" scope="row">1</th>
<td id="mwQQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwQg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td><td id="mwQw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwRA" rel="mw:WikiLink" title="Retail">Retail</a><br id="mwRQ"/> <a href="https://en.wikipedia.org/wiki/Information_technology" id="mwRg" rel="mw:WikiLink" title="Information technology">Information technology</a></td><td id="mwRw" style="text-align:center;">716 <span about="#mwt22" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwSA" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwSQ" style="text-align:center;">79.9</td><td id="mwSg" style="text-align:right;">1,576,000</td><td id="mwSw" rowspan="2"><span about="#mwt23" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"USA"}},"i":0}}]}' id="mwTA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-type="drawing" data-file-width="1235" decoding="async" height="12" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_United_States.svg" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/60px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> United States</td><td about="#mwt24" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwTQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwTg"><sup about="#mwt27" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwTw"><span class="mw-reflink-text" id="mwUA"><span class="cite-bracket" id="mwUQ">[</span>5<span class="cite-bracket" id="mwUg">]</span></span></a></sup></td></tr>
<tr id="mwUw">
<th id="mwVA" scope="col">2</th>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwVg" rel="mw:WikiLink" title="Walmart">Walmart</a></td><td id="mwVw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwWA" rel="mw:WikiLink" title="Retail">Retail</a></td><td id="mwWQ" style="text-align:center;">713 <span about="#mwt28" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwWw" style="text-align:center;">21.8</td><td id="mwXA" style="text-align:right;">2,100,000</td><td about="#mwt29" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwXQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwXg"><sup about="#mwt32" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"W"},"body":{"id":"mw-reference-text-cite_note-W-7"}}' id="cite_ref-W_7-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-W-7" id="mwXw"><span class="mw-reflink-text" id="mwYA"><span class="cite-bracket" id="mwYQ">[</span>6<span class="cite-bracket" id="mwYg">]</span></span></a></sup></td></tr>
<tr id="mwYw">
<th id="mwZA" scope="row">3</th>
<td id="mwZQ"><a href="https://en.wikipedia.org/wiki/State_Grid_Corporation_of_China" id="mwZg" rel="mw:WikiLink" title="State Grid Corporation of China">State Grid Corporation of China</a></td><td id="mwZw"><a href="https://en.wikipedia.org/wiki/Electric_utility" id="mwaA" rel="mw:WikiLink" title="Electric utility">Electricity</a></td><td id="mwaQ" style="text-align:center;">545 <span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwag" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwaw" style="text-align:center;">9.2</td><td id="mwbA" style="text-align:right;">1,361,423</td>
<td id="mwbQ"><span about="#mwt34" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwbg" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td>
<td about="#mwt35" class="table-yes2" data-mw='{"parts":["| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}]}' data-sort-value="Yes" id="mwbw" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td>
<td id="mwcA"><sup about="#mwt38" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-8"}}' id="cite_ref-8" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-8" id="mwcQ"><span class="mw-reflink-text" id="mwcg"><span class="cite-bracket" id="mwcw">[</span>7<span class="cite-bracket" id="mwdA">]</span></span></a></sup></td></tr>
<tr id="mwdQ">
<th id="mwdg" scope="row">4</th>
<td id="mwdw"><a href="https://en.wikipedia.org/wiki/Saudi_Aramco" id="mweA" rel="mw:WikiLink" title="Saudi Aramco">Saudi Aramco</a></td><td id="mweQ" rowspan="3"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_gas" id="mweg" rel="mw:WikiLink" title="Oil and gas">Oil and gas</a></td><td id="mwew" style="text-align:center;">480 <span about="#mwt39" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwfA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwfQ" style="text-align:center;">106</td><td id="mwfg" style="text-align:right;">73,311</td><td id="mwfw"><span about="#mwt40" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"Saudi Arabia"}},"i":0}}]}' id="mwgA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia"><img alt="Saudi Arabia" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_Saudi_Arabia.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/40px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/60px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> Saudi Arabia</td><td about="#mwt41" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwgQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwgg"><sup about="#mwt44" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-9"}}' id="cite_ref-9" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-9" id="mwgw"><span class="mw-reflink-text" id="mwhA"><span class="cite-bracket" id="mwhQ">[</span>8<span class="cite-bracket" id="mwhg">]</span></span></a></sup></td></tr>
<tr id="mwhw">
<th id="mwiA" scope="row">5</th>
<td id="mwiQ"><a href="https://en.wikipedia.org/wiki/China_National_Petroleum_Corporation" id="mwig" rel="mw:WikiLink" title="China National Petroleum Corporation">China National Petroleum Corporation</a></td><td id="mwiw" style="text-align:center;">476 <span about="#mwt45" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwjA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwjQ" style="text-align:center;">25.2</td><td id="mwjg" style="text-align:right;">1,026,301</td><td id="mwjw" rowspan="2"><span about="#mwt46" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwkA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td><td about="#mwt47" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwkQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwkg"><sup about="#mwt50" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-10"}}' id="cite_ref-10" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-10" id="mwkw"><span class="mw-reflink-text" id="mwlA"><span class="cite-bracket" id="mwlQ">[</span>9<span class="cite-bracket" id="mwlg">]</span></span></a></sup></td></tr>
<tr id="mwlw">
<th id="mwmA" scope="row">6</th>
<td id="mwmQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/China_Petrochemical_Corporation" id="mwmg" rel="mw:WikiLink" title="China Petrochemical Corporation">China Petrochemical Corporation</a></td>

In [9]:
table = soup.find_all('table')[0]

In [10]:
soup.find('table', class_ = 'wikitable sortable sticky-header-multi sort-under')

<table class="wikitable sortable sticky-header-multi sort-under" id="mwKQ" style="text-align:left;">
<tbody id="mwKg"><tr id="mwKw">
<th id="mwLA" rowspan="2" scope="col">Ranks</th>
<th id="mwLQ" rowspan="2" scope="col">Name</th>
<th id="mwLg" rowspan="2" scope="col">Industry</th>
<th id="mwLw" scope="col">Revenue</th>
<th id="mwMA" scope="col">Profit</th>
<th id="mwMQ" rowspan="2" scope="col">Employees</th>
<th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>
<th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>
<th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th></tr>
<tr id="mwPA">
<th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th></tr>
<tr id="mwPw">
<th id="mwQA" scope="row">1</th>
<td id="mwQQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwQg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td><td id="mwQw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwRA" rel="mw:WikiLink" title="Retail">Retail</a><br id="mwRQ"/> <a href="https://en.wikipedia.org/wiki/Information_technology" id="mwRg" rel="mw:WikiLink" title="Information technology">Information technology</a></td><td id="mwRw" style="text-align:center;">716 <span about="#mwt22" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwSA" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwSQ" style="text-align:center;">79.9</td><td id="mwSg" style="text-align:right;">1,576,000</td><td id="mwSw" rowspan="2"><span about="#mwt23" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"USA"}},"i":0}}]}' id="mwTA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-type="drawing" data-file-width="1235" decoding="async" height="12" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_United_States.svg" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/60px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> United States</td><td about="#mwt24" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwTQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwTg"><sup about="#mwt27" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwTw"><span class="mw-reflink-text" id="mwUA"><span class="cite-bracket" id="mwUQ">[</span>5<span class="cite-bracket" id="mwUg">]</span></span></a></sup></td></tr>
<tr id="mwUw">
<th id="mwVA" scope="col">2</th>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwVg" rel="mw:WikiLink" title="Walmart">Walmart</a></td><td id="mwVw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwWA" rel="mw:WikiLink" title="Retail">Retail</a></td><td id="mwWQ" style="text-align:center;">713 <span about="#mwt28" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwWw" style="text-align:center;">21.8</td><td id="mwXA" style="text-align:right;">2,100,000</td><td about="#mwt29" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwXQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwXg"><sup about="#mwt32" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"W"},"body":{"id":"mw-reference-text-cite_note-W-7"}}' id="cite_ref-W_7-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-W-7" id="mwXw"><span class="mw-reflink-text" id="mwYA"><span class="cite-bracket" id="mwYQ">[</span>6<span class="cite-bracket" id="mwYg">]</span></span></a></sup></td></tr>
<tr id="mwYw">
<th id="mwZA" scope="row">3</th>
<td id="mwZQ"><a href="https://en.wikipedia.org/wiki/State_Grid_Corporation_of_China" id="mwZg" rel="mw:WikiLink" title="State Grid Corporation of China">State Grid Corporation of China</a></td><td id="mwZw"><a href="https://en.wikipedia.org/wiki/Electric_utility" id="mwaA" rel="mw:WikiLink" title="Electric utility">Electricity</a></td><td id="mwaQ" style="text-align:center;">545 <span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwag" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwaw" style="text-align:center;">9.2</td><td id="mwbA" style="text-align:right;">1,361,423</td>
<td id="mwbQ"><span about="#mwt34" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwbg" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td>
<td about="#mwt35" class="table-yes2" data-mw='{"parts":["| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}]}' data-sort-value="Yes" id="mwbw" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td>
<td id="mwcA"><sup about="#mwt38" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-8"}}' id="cite_ref-8" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-8" id="mwcQ"><span class="mw-reflink-text" id="mwcg"><span class="cite-bracket" id="mwcw">[</span>7<span class="cite-bracket" id="mwdA">]</span></span></a></sup></td></tr>
<tr id="mwdQ">
<th id="mwdg" scope="row">4</th>
<td id="mwdw"><a href="https://en.wikipedia.org/wiki/Saudi_Aramco" id="mweA" rel="mw:WikiLink" title="Saudi Aramco">Saudi Aramco</a></td><td id="mweQ" rowspan="3"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_gas" id="mweg" rel="mw:WikiLink" title="Oil and gas">Oil and gas</a></td><td id="mwew" style="text-align:center;">480 <span about="#mwt39" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwfA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwfQ" style="text-align:center;">106</td><td id="mwfg" style="text-align:right;">73,311</td><td id="mwfw"><span about="#mwt40" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"Saudi Arabia"}},"i":0}}]}' id="mwgA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia"><img alt="Saudi Arabia" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_Saudi_Arabia.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/40px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/60px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> Saudi Arabia</td><td about="#mwt41" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwgQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwgg"><sup about="#mwt44" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-9"}}' id="cite_ref-9" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-9" id="mwgw"><span class="mw-reflink-text" id="mwhA"><span class="cite-bracket" id="mwhQ">[</span>8<span class="cite-bracket" id="mwhg">]</span></span></a></sup></td></tr>
<tr id="mwhw">
<th id="mwiA" scope="row">5</th>
<td id="mwiQ"><a href="https://en.wikipedia.org/wiki/China_National_Petroleum_Corporation" id="mwig" rel="mw:WikiLink" title="China National Petroleum Corporation">China National Petroleum Corporation</a></td><td id="mwiw" style="text-align:center;">476 <span about="#mwt45" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwjA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwjQ" style="text-align:center;">25.2</td><td id="mwjg" style="text-align:right;">1,026,301</td><td id="mwjw" rowspan="2"><span about="#mwt46" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwkA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td><td about="#mwt47" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwkQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwkg"><sup about="#mwt50" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-10"}}' id="cite_ref-10" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-10" id="mwkw"><span class="mw-reflink-text" id="mwlA"><span class="cite-bracket" id="mwlQ">[</span>9<span class="cite-bracket" id="mwlg">]</span></span></a></sup></td></tr>
<tr id="mwlw">
<th id="mwmA" scope="row">6</th>
<td id="mwmQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/China_Petrochemical_Corporation" id="mwmg" rel="mw:WikiLink" title="China Petrochemical Corporation">China Petrochemical Corporation</a></td>

In [11]:
table.find_all('th', scope = 'col')

[<th id="mwLA" rowspan="2" scope="col">Ranks</th>,
 <th id="mwLQ" rowspan="2" scope="col">Name</th>,
 <th id="mwLg" rowspan="2" scope="col">Industry</th>,
 <th id="mwLw" scope="col">Revenue</th>,
 <th id="mwMA" scope="col">Profit</th>,
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>,
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>,
 <th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>,
 <th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th>,
 <th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th>,
 <th id="mwVA" scope="col">2</th>]

In [12]:
table.find_all(
    lambda tag: tag.name == "th" and (
        (tag.has_attr("scope") and tag["scope"] == "col")
         and 
        (tag.has_attr('id') and tag['id'] != 'mwVA')
    )
)

[<th id="mwLA" rowspan="2" scope="col">Ranks</th>,
 <th id="mwLQ" rowspan="2" scope="col">Name</th>,
 <th id="mwLg" rowspan="2" scope="col">Industry</th>,
 <th id="mwLw" scope="col">Revenue</th>,
 <th id="mwMA" scope="col">Profit</th>,
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>,
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>,
 <th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>,
 <th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th>,
 <th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th>]

In [13]:
semi_final_table = table.find_all(
    lambda tag: tag.name == "th" and (
        (tag.has_attr("scope") and tag["scope"] == "col")
         and 
        (tag.has_attr('id') and tag['id'] != 'mwVA')
        and 
        (tag.has_attr('id') and tag['id'] != 'mwPQ')
    )
) #removed usd in bilions wiht the last line

In [14]:
semi_final_table

[<th id="mwLA" rowspan="2" scope="col">Ranks</th>,
 <th id="mwLQ" rowspan="2" scope="col">Name</th>,
 <th id="mwLg" rowspan="2" scope="col">Industry</th>,
 <th id="mwLw" scope="col">Revenue</th>,
 <th id="mwMA" scope="col">Profit</th>,
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>,
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>,
 <th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>,
 <th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th>]

In [15]:
table.find_all(
    lambda tag: tag.name == "th" and (
        (tag.has_attr("scope") and tag["scope"] == "col")
         and 
        (tag.has_attr('id') and tag['id'] != 'mwVA')
        and 
        (tag.has_attr('id') and tag['id'] != 'mwPQ')
        and
        (tag.has_attr('id') and tag['id'] != 'mwOQ')
        and
        (tag.has_attr('id') and tag['id'] != 'mwNw')
    )
)

[<th id="mwLA" rowspan="2" scope="col">Ranks</th>,
 <th id="mwLQ" rowspan="2" scope="col">Name</th>,
 <th id="mwLg" rowspan="2" scope="col">Industry</th>,
 <th id="mwLw" scope="col">Revenue</th>,
 <th id="mwMA" scope="col">Profit</th>,
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>,
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>]

In [16]:
title = table.find_all(
    lambda tag: tag.name == "th" and (
        (tag.has_attr("scope") and tag["scope"] == "col")
         and 
        (tag.has_attr('id') and tag['id'] != 'mwVA')
        and 
        (tag.has_attr('id') and tag['id'] != 'mwPQ')
        and
        (tag.has_attr('id') and tag['id'] != 'mwOQ')
        and
        (tag.has_attr('id') and tag['id'] != 'mwNw')
    )
)

In [17]:
title = table.find_all(
    lambda tag: tag.name == "th" and (
        (tag.has_attr("scope") and tag["scope"] == "col")
         and 
        (tag.has_attr('id') and tag['id'] != 'mwVA')
        and 
        (tag.has_attr('id') and tag['id'] != 'mwPQ')
    )
)

In [18]:
title_table = [title.text.strip() for title in title]

In [19]:
print(title_table)

['Ranks', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees', 'Headquarters[note 1]', 'State-owned', 'Ref.']

In [20]:
import pandas as pd

c:\Users\Riad\Anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [21]:
df = pd.DataFrame(columns= title_table)

In [22]:
df

Empty DataFrame
Columns: [Ranks, Name, Industry, Revenue, Profit, Employees, Headquarters[note 1], State-owned, Ref.]
Index: []

In [23]:
col_data = table.find_all('tr')

In [39]:

num_cols = len(df)

# Tracks {column_index: (remaining_rowspan_count, value)}
active_rowspans = {}

rows_out = []
for row in col_data[2:]:
    cells = row.find_all('td')
    row_values = [None] * num_cols
    col_idx = 0

    for cell in cells:
        # skip columns currently filled by an active rowspan from above
        while col_idx in active_rowspans and active_rowspans[col_idx][0] > 0:
            row_values[col_idx] = active_rowspans[col_idx][1]
            active_rowspans[col_idx] = (active_rowspans[col_idx][0] - 1, active_rowspans[col_idx][1])
            col_idx += 1

        text = cell.text.strip()
        row_values[col_idx] = text

        rowspan = int(cell.get('rowspan', 1))
        if rowspan > 1:
            active_rowspans[col_idx] = (rowspan - 1, text)

        col_idx += 1

    # fill any trailing rowspan columns after the loop
    while col_idx < num_cols:
        if col_idx in active_rowspans and active_rowspans[col_idx][0] > 0:
            row_values[col_idx] = active_rowspans[col_idx][1]
            active_rowspans[col_idx] = (active_rowspans[col_idx][0] - 1, active_rowspans[col_idx][1])
        col_idx += 1

    rows_out.append(row_values)

df = pd.DataFrame(rows_out, columns= title_table)

ValueError: 9 columns passed, passed data had 50 columns

In [38]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,Amazon,Retail Information technology,716,79.9,"1,576,000",United States,,[5],None,None,...,None,None,None,None,None,None,None,None,None,None
1,Walmart,Retail,713,21.8,"2,100,000",United States,,[6],None,None,...,None,None,None,None,None,None,None,None,None,None
2,State Grid Corporation of China,Electricity,545,9.2,"1,361,423",China,,[7],None,None,...,None,None,None,None,None,None,None,None,None,None
3,Saudi Aramco,Oil and gas,480,106,"73,311",Saudi Arabia,,[8],None,None,...,None,None,None,None,None,None,None,None,None,None
4,China National Petroleum Corporation,Oil and gas,476,25.2,"1,026,301",China,,[9],None,None,...,None,None,None,None,None,None,None,None,None,None
5,China Petrochemical Corporation,Oil and gas,429,9.3,"513,434",China,,[10],None,None,...,None,None,None,None,None,None,None,None,None,None
6,Apple,Information technology,416,112,"166,000",United States,,[11],None,None,...,None,None,None,None,None,None,None,None,None,None
7,Alphabet,Information technology,402,132,"190,820",United States,,[12],None,None,...,None,None,None,None,None,None,None,None,None,None
8,UnitedHealth Group,Healthcare,400,14.4,"400,000",United States,,[13],None,None,...,None,None,None,None,None,None,None,None,None,None
9,Berkshire Hathaway,Financials,371,88.9,"392,400",United States,,[14],None,None,...,None,None,None,None,None,None,None,None,None,None
10,CVS Health,Healthcare,357,8.3,"259,500",United States,,[15],None,None,...,None,None,None,None,None,None,None,None,None,None
11,Volkswagen Group,Automotive,348,17.9,"684,025",Germany,,[16],None,None,...,None,None,None,None,None,None,None,None,None,None
12,ExxonMobil,Oil and gas,344,36.0,"61,500",United States,,[17],None,None,...,None,None,None,None,None,None,None,None,None,None
13,Vitol,Commodities,331,13.0,"1,560",Switzerland,,[18][19],None,None,...,None,None,None,None,None,None,None,None,None,None
14,Shell,Oil and gas,323,19.3,"103,000",United Kingdom,,[20],None,None,...,None,None,None,None,None,None,None,None,None,None
15,China State Construction Engineering,Construction,320,4.2,"382,894",China,,[21],None,None,...,None,None,None,None,None,None,None,None,None,None
16,Toyota,Automotive,312,34.2,"380,793",Japan,,[22],None,None,...,None,None,None,None,None,None,None,None,None,None
17,McKesson,Healthcare,308,3.0,"48,000",United States,,[23],None,None,...,None,None,None,None,None,None,None,None,None,None
18,Microsoft,Information technology,281,101,"228,000",United States,,[24],None,None,...,None,None,None,None,None,None,None,None,None,None
19,Cencora,Healthcare,262,1.7,"44,000",United States,,[25],None,None,...,None,None,None,None,None,None,None,None,None,None
20,Trafigura,Commodities,244,7.3,"12,479",Singapore,,[26],None,None,...,None,None,None,None,None,None,None,None,None,None
21,Costco,Retail,242,6.2,"316,000",United States,,[27],None,None,...,None,None,None,None,None,None,None,None,None,None
22,JPMorgan Chase,Financials,239,49.5,"309,926",United States,,[28],None,None,...,None,None,None,None,None,None,None,None,None,None
23,Industrial and Commercial Bank of China,Financials,222,51.4,"419,252",China,,[29],None,None,...,None,None,None,None,None,None,None,None,None,None
24,Schwarz Gruppe,Retail,220,n/a,"604,000",Germany,,[30],None,None,...,None,None,None,None,None,None,None,None,None,None
25,TotalEnergies,Oil and gas,218,21.3,"102,579",France,,[31],None,None,...,None,None,None,None,None,None,None,None,None,None
26,Glencore,Commodities,217,4.2,"83,426",Switzerland,,[32],None,None,...,None,None,None,None,None,None,None,None,None,None
27,Nvidia,Semiconductors,215,120,"36,000",United States,,[33],None,None,...,None,None,None,None,None,None,None,None,None,None
28,BP,Oil and gas,213,15.2,"79,400",United Kingdom,,[34],None,None,...,None,None,None,None,None,None,None,None,None,None
29,Cardinal Health,Healthcare,205,0.26,"47,520",United States,,[35],None,None,...,None,None,None,None,None,None,None,None,None,None
30,Stellantis,Automotive,204,20.1,"258,275",Netherlands,,[36],None,None,...,None,None,None,None,None,None,None,None,None,None
31,Chevron,Oil and gas,200,21.3,"45,600",United States,,[37],None,None,...,None,None,None,None,None,None,None,None,None,None
32,China Construction Bank,Financials,199,46.9,"376,871",China,,[38],None,None,...,None,None,None,None,None,None,None,None,None,None
33,Samsung Electronics,Electronics,198,11.0,"267,860",South Korea,,[39],None,None,...,None,None,None,None,None,None,None,None,None,None
34,Foxconn,Electronics,197,4.5,"621,393",Taiwan,,[40],None,None,...,None,None,None,None,None,None,None,None,None,None
35,Cigna,Healthcare,195,5.1,"71,413",United States,,[41],None,None,...,None,None,None,None,None,None,None,None,None,None
36,Agricultural Bank of China,Financials,192,38.0,"451,003",China,,[42],None,None,...,None,None,None,None,None,None,None,None,None,None
37,China Railway Engineering Corporation,Construction,178,2.1,"314,149",China,,[43],None,None,...,None,None,None,None,None,None,None,None,None,None
38,Cargill,Conglomerate,177,17.6,"160,000",United States,,[44],None,None,...,None,None,None,None,None,None,None,None,None,None
39,Ford Motor Company,Automotive,176,4.3,"177,000",United States,,[45],None,None,...,None,None,None,None,None,None,None,None,None,None
40,Bank of China,Financials,172,32.7,"306,931",China,,[46],None,None,...,None,None,None,None,None,None,None,None,None,None
41,Bank of America,Financials,171,26.5,"212,985",United States,,[47],None,None,...,None,None,None,None,None,None,None,None,None,None
42,General Motors,Automotive,171,10.1,"163,000",United States,,[48],None,None,...,None,None,None,None,None,None,None,None,None,None
43,Elevance Health,Healthcare,171,5.9,"104,900",United States,,[49],None,None,...,None,None,None,None,None,None,None,None,None,None
44,BMW Group,Automotive,168,12.2,"154,950",Germany,,[50],None,None,...,None,None,None,None,None,None,None,None,None,None
45,Mercedes-Benz Group,Automotive,165,15.4,"166,056",Germany,,[51],None,None,...,None,None,None,None,None,None,None,None,None,None
46,Meta Platforms,Social media,164,62.3,"78,450",United States,,[52],None,None,...,None,None,None,None,None,None,None,None,None,None
47,China Railway Construction Corporation,Construction,160,1.7,"336,433",China,,[53],None,None,...,None,None,None,None,None,None,None,None,None,None
48,Baowu,Steel,157,2.4,"258,697",China,,[54],None,None,...,None,None,None,None,None,None,None,None,None,None
49,Citigroup,Financials,156,9.2,"237,925",United States,,[55],None,None,...,None,None,None,None,None,None,None,None,None,None

In [25]:
for row in col_data[2:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    lenght = len(df)
    if lenght > len(individual_row_data):
        individual_row_data = 
    df.loc[lenght] = individual_row_data

SyntaxError: invalid syntax (4133982373.py, line 6)